create table
  logs.data_exports (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    by_user uuid not null default auth.uid (),
    constraint data_exports_pkey primary key (id)
  ) tablespace pg_default;