create table
  public.data_exports (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    by_user uuid not null,
    constraint data_exports_pkey primary key (id),
    constraint data_exports_by_user_fkey foreign key (by_user) references profiles (id)
  ) tablespace pg_default;
  